# Elasticsearch Configuration for Spatial Tag Platform
# Version: 8.0.0 (xpack)

#----------------------
# Cluster Settings
#----------------------
cluster.name: spatial-tag-cluster
cluster.initial_master_nodes: ["${NODE_NAME}"]
discovery.seed_hosts: ["${SEED_HOSTS}"]
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: "85%"
cluster.routing.allocation.disk.watermark.high: "90%"
cluster.routing.allocation.awareness.attributes: zone
cluster.routing.allocation.enable: all
cluster.routing.rebalance.enable: all

#----------------------
# Node Settings
#----------------------
node.name: "${NODE_NAME}"
node.roles: ["master", "data", "ingest"]
node.attr.zone: "${AVAILABILITY_ZONE}"
node.master: true
node.data: true
node.ingest: true
node.max_local_storage_nodes: 1

#----------------------
# Path Settings
#----------------------
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
path.repo: /var/lib/elasticsearch/backup

#----------------------
# Network Settings
#----------------------
network.host: 0.0.0.0
network.bind_host: 0.0.0.0
network.publish_host: "${PUBLISH_HOST}"
http.port: 9200
transport.port: 9300
http.cors.enabled: true
http.cors.allow-origin: "*"
http.max_content_length: "100mb"
http.compression: true

#----------------------
# Memory Settings
#----------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: "30%"
indices.queries.cache.size: "20%"
indices.fielddata.cache.size: "30%"
indices.breaker.total.use_real_memory: true
indices.breaker.fielddata.limit: "40%"
indices.breaker.request.limit: "60%"

#----------------------
# Security Settings
#----------------------
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
xpack.security.audit.enabled: true
xpack.security.audit.logfile.events.include: ["authentication_success", "authentication_failure", "access_denied", "connection_denied"]
xpack.security.authc.api_key.enabled: true
xpack.security.authc.token.enabled: true

#----------------------
# Monitoring Settings
#----------------------
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: "10s"
xpack.monitoring.history.duration: "7d"
xpack.monitoring.collection.cluster.stats.timeout: "10s"
xpack.monitoring.collection.node.stats.timeout: "10s"

#----------------------
# Index Settings
#----------------------
action.auto_create_index: ".monitoring-*,.watches,.triggered_watches,.watcher-history-*"
indices.recovery.max_bytes_per_sec: "40mb"
indices.fielddata.cache.size: "30%"
indices.query.bool.max_clause_count: 2048
indices.lifecycle.history.max_age: "7d"
indices.lifecycle.poll_interval: "10m"

#----------------------
# Thread Pool Settings
#----------------------
thread_pool.write.size: 32
thread_pool.write.queue_size: 1000
thread_pool.search.size: 16
thread_pool.search.queue_size: 1000
thread_pool.analyze.size: 8
thread_pool.analyze.queue_size: 200
thread_pool.get.size: 8
thread_pool.get.queue_size: 200