# Kubernetes Secrets manifest for Spatial Tag platform
# Version: 1.0.0
# Integrates with HashiCorp Vault for secure secret management and automated rotation

apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: spatial-tag
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/role: "api-gateway"
    vault.hashicorp.com/secret-rotation-period: "24h"
    vault.hashicorp.com/namespace: "spatial-tag"
    vault.hashicorp.com/auth-path: "auth/kubernetes"
    vault.hashicorp.com/tls-secret: "vault-tls"
    vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
type: Opaque
data:
  jwt_secret: ${VAULT_JWT_SECRET}
  jwt_refresh_secret: ${VAULT_JWT_REFRESH_SECRET}
  tls_key: ${VAULT_TLS_KEY}
  tls_cert: ${VAULT_TLS_CERT}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: spatial-tag
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: "update"
    vault.hashicorp.com/role: "user-service"
    vault.hashicorp.com/secret-rotation-period: "24h"
    vault.hashicorp.com/namespace: "spatial-tag"
    vault.hashicorp.com/auth-path: "auth/kubernetes"
    vault.hashicorp.com/tls-secret: "vault-tls"
    vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
    vault.hashicorp.com/secret-volume-path: "/vault/secrets"
type: Opaque
data:
  db_user: ${VAULT_DB_USER}
  db_password: ${VAULT_DB_PASSWORD}
  jwt_private_key: ${VAULT_JWT_PRIVATE_KEY}
  jwt_public_key: ${VAULT_JWT_PUBLIC_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
  namespace: spatial-tag
type: kubernetes.io/tls
data:
  tls.crt: ${VAULT_TLS_CRT}
  tls.key: ${VAULT_TLS_KEY}
  ca.crt: ${VAULT_CA_CRT}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  namespace: spatial-tag
  annotations:
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  VAULT_ADDR: aHR0cHM6Ly92YXVsdC5zcGF0aWFsLXRhZy5zdmM6ODIwMA== # https://vault.spatial-tag.svc:8200
  KUBERNETES_NAMESPACE: c3BhdGlhbC10YWc= # spatial-tag
  SECRET_ROTATION_SCHEDULE: MCAwICogKiAq # 0 0 * * *