# SwiftLint configuration for SpatialTag iOS Application
# Version: 0.50.3

# Paths to include/exclude from linting
included:
  - src/ios/SpatialTag
excluded:
  - src/ios/Pods
  - src/ios/SpatialTagTests
  - src/ios/SpatialTagUITests
  - src/ios/fastlane
  - src/ios/DerivedData

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - missing_docs
  - closure_spacing
  - explicit_init
  - force_unwrapping
  - implicit_return
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - spatial_coordinate_naming
  - ar_session_handling
  - lidar_processing_complexity

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100
  ignores_comments: true

type_body_length:
  warning: 250
  error: 350

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

type_name:
  min_length: 3
  max_length: 50
  excluded:
    - AR
    - 3D

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y
    - z
    - ar
    - dx
    - dy
    - dz
  validates_start_with_lowercase: true

nesting:
  type_level:
    warning: 2
    error: 3

# Error-level rules
force_cast: error
force_try: error
force_unwrapping:
  severity: error
  excluded:
    - ARSession
    - LiDARSession

# Warning-level rules
implicit_getter: warning
redundant_discardable_let: warning
vertical_parameter_alignment: error
void_return: warning
trailing_comma: warning
trailing_semicolon: error
mark: warning
empty_count: warning
todo: warning

# Documentation rules
missing_docs:
  warning: true
  requires_docs_for:
    - public
    - open
    - internal
  excluded:
    - SpatialTests

# Custom rules for AR and spatial features
private_outlet: warning
prohibited_super_call: error
redundant_nil_coalescing: warning
switch_case_on_newline: warning
closure_spacing: warning
explicit_init: warning
implicit_return: warning

# Spatial computing specific rules
spatial_rules:
  coordinate_validation: warning
  lidar_processing:
    max_complexity: 15
    requires_documentation: true
  ar_session:
    force_unwrap_allowed: true
    requires_error_handling: true