platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'SpatialTag' do
  pod 'ARKit', '~> 6.0'
  pod 'Firebase/Core', '~> 10.0.0'
  pod 'Firebase/Messaging', '~> 10.0.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Performance'
  pod 'Sentry'
  pod 'DatadogSDK'
  pod 'MapboxMaps'
  pod 'MapboxCoreNavigation'
  pod 'MapboxNavigation'
  pod 'Stripe'
  pod 'StripeApplePay'
  pod 'SwiftProtobuf'
  pod 'gRPC-Swift'
  pod 'KeychainAccess'
  pod 'CryptoSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'lottie-ios'
  pod 'PromiseKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'SwiftGen'

  target 'SpatialTagTests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'SpatialTagUITests' do
    inherit! :search_paths
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['SWIFT_VERSION'] = '5.9'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end