// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  protoc-gen-go v1.28.0
//  protoc        v3.21.0
// source: tag.proto

package proto

import (
    "context"
    protoreflect "google.golang.org/protobuf/reflect/protoreflect"  // v1.28.0
    protoimpl "google.golang.org/protobuf/runtime/protoimpl"        // v1.28.0
    timestamppb "google.golang.org/protobuf/types/known/timestamppb" // v1.28.0
    grpc "google.golang.org/grpc"                                   // v1.45.0
    spatial "spatialtag/backend/proto/spatial"
)

const (
    // Verify that this generated code is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
    // Verify that runtime/protoimpl is sufficiently up-to-date.
    _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enhanced tag visibility levels
type TagVisibility int32

const (
    TagVisibility_TAG_VISIBILITY_UNSPECIFIED TagVisibility = 0
    TagVisibility_TAG_VISIBILITY_PUBLIC      TagVisibility = 1
    TagVisibility_TAG_VISIBILITY_PRIVATE     TagVisibility = 2
    TagVisibility_TAG_VISIBILITY_ELITE_ONLY  TagVisibility = 3
)

// Map for tag visibility enum names
var TagVisibility_name = map[int32]string{
    0: "TAG_VISIBILITY_UNSPECIFIED",
    1: "TAG_VISIBILITY_PUBLIC",
    2: "TAG_VISIBILITY_PRIVATE",
    3: "TAG_VISIBILITY_ELITE_ONLY",
}

// Map for tag visibility enum values
var TagVisibility_value = map[string]int32{
    "TAG_VISIBILITY_UNSPECIFIED": 0,
    "TAG_VISIBILITY_PUBLIC":      1,
    "TAG_VISIBILITY_PRIVATE":     2,
    "TAG_VISIBILITY_ELITE_ONLY":  3,
}

// Enhanced tag status tracking
type TagStatus int32

const (
    TagStatus_TAG_STATUS_UNSPECIFIED TagStatus = 0
    TagStatus_TAG_STATUS_ACTIVE      TagStatus = 1
    TagStatus_TAG_STATUS_EXPIRED     TagStatus = 2
    TagStatus_TAG_STATUS_DELETED     TagStatus = 3
)

// Map for tag status enum names
var TagStatus_name = map[int32]string{
    0: "TAG_STATUS_UNSPECIFIED",
    1: "TAG_STATUS_ACTIVE",
    2: "TAG_STATUS_EXPIRED",
    3: "TAG_STATUS_DELETED",
}

// Map for tag status enum values
var TagStatus_value = map[string]int32{
    "TAG_STATUS_UNSPECIFIED": 0,
    "TAG_STATUS_ACTIVE":      1,
    "TAG_STATUS_EXPIRED":     2,
    "TAG_STATUS_DELETED":     3,
}

// Enhanced Tag message with comprehensive status and visibility support
type Tag struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
    CreatorId       string                 `protobuf:"bytes,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
    Location        *spatial.Location      `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
    Content         string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
    CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
    ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
    VisibilityRadius float64               `protobuf:"fixed64,7,opt,name=visibility_radius,json=visibilityRadius,proto3" json:"visibility_radius,omitempty"`
    Visibility      TagVisibility          `protobuf:"varint,8,opt,name=visibility,proto3,enum=TagVisibility" json:"visibility,omitempty"`
    Status          TagStatus              `protobuf:"varint,9,opt,name=status,proto3,enum=TagStatus" json:"status,omitempty"`
}

// Enhanced CreateTagRequest with validation support
type CreateTagRequest struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    CreatorId        string            `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
    Location         *spatial.Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
    Content          string            `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
    ExpirationHours  int32            `protobuf:"varint,4,opt,name=expiration_hours,json=expirationHours,proto3" json:"expiration_hours,omitempty"`
    VisibilityRadius float64          `protobuf:"fixed64,5,opt,name=visibility_radius,json=visibilityRadius,proto3" json:"visibility_radius,omitempty"`
    Visibility       TagVisibility     `protobuf:"varint,6,opt,name=visibility,proto3,enum=TagVisibility" json:"visibility,omitempty"`
}

// Enhanced GetNearbyTagsRequest with comprehensive filtering
type GetNearbyTagsRequest struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Location      *spatial.Location `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
    RadiusMeters  float64          `protobuf:"fixed64,2,opt,name=radius_meters,json=radiusMeters,proto3" json:"radius_meters,omitempty"`
    UserId        string           `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
    IncludeExpired bool            `protobuf:"varint,4,opt,name=include_expired,json=includeExpired,proto3" json:"include_expired,omitempty"`
    Visibility     TagVisibility    `protobuf:"varint,5,opt,name=visibility,proto3,enum=TagVisibility" json:"visibility,omitempty"`
}

// Enhanced GetNearbyTagsResponse with metadata
type GetNearbyTagsResponse struct {
    state         protoimpl.MessageState
    sizeCache     protoimpl.SizeCache
    unknownFields protoimpl.UnknownFields

    Tags                []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
    SearchRadiusMeters  float64               `protobuf:"fixed64,2,opt,name=search_radius_meters,json=searchRadiusMeters,proto3" json:"search_radius_meters,omitempty"`
    Timestamp          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

// Enhanced TagService interface with comprehensive management capabilities
type TagServiceServer interface {
    CreateTag(context.Context, *CreateTagRequest) (*Tag, error)
    GetTag(context.Context, *GetTagRequest) (*Tag, error)
    UpdateTag(context.Context, *UpdateTagRequest) (*Tag, error)
    DeleteTag(context.Context, *DeleteTagRequest) (*Tag, error)
    GetNearbyTags(context.Context, *GetNearbyTagsRequest) (*GetNearbyTagsResponse, error)
    StreamTagUpdates(*StreamTagUpdatesRequest, TagService_StreamTagUpdatesServer) error
}

// Enhanced TagServiceClient interface
type TagServiceClient interface {
    CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*Tag, error)
    GetTag(ctx context.Context, in *GetTagRequest, opts ...grpc.CallOption) (*Tag, error)
    UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*Tag, error)
    DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*Tag, error)
    GetNearbyTags(ctx context.Context, in *GetNearbyTagsRequest, opts ...grpc.CallOption) (*GetNearbyTagsResponse, error)
    StreamTagUpdates(ctx context.Context, in *StreamTagUpdatesRequest, opts ...grpc.CallOption) (TagService_StreamTagUpdatesClient, error)
}

// RegisterTagServiceServer registers the server with the gRPC framework
func RegisterTagServiceServer(s grpc.ServiceRegistrar, srv TagServiceServer) {
    s.RegisterService(&_TagService_serviceDesc, srv)
}

// NewTagServiceClient creates a new client with enhanced capabilities
func NewTagServiceClient(cc grpc.ClientConnInterface) TagServiceClient {
    return &tagServiceClient{cc}
}

// Implementation of protobuf message interface
func (x *Tag) ProtoMessage() {}

// Reset implementation for Tag message
func (x *Tag) Reset() {
    *x = Tag{}
    if protoimpl.UnsafeEnabled {
        mi := &file_tag_proto_msgTypes[0]
        ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
        ms.StoreMessageInfo(mi)
    }
}