groups:
  # Service Health Monitoring
  - name: service_health
    rules:
      # Critical service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute, affecting system availability target"

      - alert: HighResponseTime
        expr: rate(http_request_duration_seconds{quantile="0.95"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time for {{ $labels.job }}"
          description: "95th percentile response time is above 100ms threshold, impacting user experience"

      - alert: ServiceAvailabilityBelowSLA
        expr: avg_over_time(up[24h]) * 100 < 99.9
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "Service availability below SLA for {{ $labels.job }}"
          description: "Service availability has dropped below 99.9% SLA threshold over 24h period"

  # Resource Utilization Monitoring
  - name: resource_utilization
    rules:
      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage for {{ $labels.container }}"
          description: "Container CPU usage above 80% of allocated limit for 5 minutes"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage for {{ $labels.container }}"
          description: "Container memory usage above 80% of allocated limit for 5 minutes"

      - alert: DiskSpaceRunningLow
        expr: disk_free_bytes / disk_total_bytes * 100 < 20
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.device }}"
          description: "Disk space utilization above 80% on {{ $labels.device }}"

  # Spatial Engine Performance
  - name: spatial_engine
    rules:
      - alert: HighLiDARProcessingLatency
        expr: lidar_processing_latency_seconds > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High LiDAR processing latency"
          description: "LiDAR processing latency above 500ms threshold, affecting real-time spatial awareness"

      - alert: SpatialEngineCPUThrottling
        expr: rate(container_cpu_cfs_throttled_seconds_total{container=~"spatial-engine.*"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Spatial Engine CPU throttling detected"
          description: "CPU throttling observed in Spatial Engine, may impact LiDAR processing performance"

      - alert: HighSpatialDataProcessingErrors
        expr: rate(spatial_processing_errors_total[5m]) > 0.05
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High spatial data processing error rate"
          description: "Spatial data processing error rate exceeds 5% threshold"

  # Business Metrics and KPIs
  - name: business_metrics
    rules:
      - alert: LowDailyActiveUsers
        expr: sum(rate(user_session_total[24h])) < 0.3
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Low daily active users"
          description: "Daily active user rate below 30% target, requires investigation"

      - alert: HighTagCreationFailureRate
        expr: rate(tag_creation_failures_total[5m]) / rate(tag_creation_attempts_total[5m]) > 0.1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High tag creation failure rate"
          description: "Tag creation failure rate above 10% threshold for 15 minutes"

      - alert: LowUserEngagement
        expr: avg(user_session_duration_seconds) < 900
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Low average session duration"
          description: "Average session duration below 15-minute target, indicating potential engagement issues"

      - alert: LowTagCreationRate
        expr: sum(rate(tag_creation_total[1w])) / sum(rate(active_users_total[1w])) < 5
        for: 24h
        labels:
          severity: warning
        annotations:
          summary: "Low tag creation rate"
          description: "Weekly average tag creation rate below 5 tags per active user target"

  # Infrastructure Health
  - name: infrastructure_health
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate exceeds 5% threshold across all services"

      - alert: NetworkLatencyHigh
        expr: rate(network_latency_seconds[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High network latency"
          description: "Network latency exceeds 50ms threshold"

      - alert: DatabaseConnectionErrors
        expr: rate(database_connection_errors_total[5m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Database connection errors detected"
          description: "Multiple database connection errors observed in the last 5 minutes"